// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyxAQfM_tmh4k7S7S0Kl2C1hL7so5qv68',
    appId: '1:605657235035:web:0ddfaedccdf9faf858897e',
    messagingSenderId: '605657235035',
    projectId: 'shuttleapp-260f8',
    authDomain: 'shuttleapp-260f8.firebaseapp.com',
    databaseURL: 'https://shuttleapp-260f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shuttleapp-260f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA52DaHoVIkV_GK3GQpo2JLBGpy-CCdyhA',
    appId: '1:605657235035:android:b6fb1eb2848bc21658897e',
    messagingSenderId: '605657235035',
    projectId: 'shuttleapp-260f8',
    databaseURL: 'https://shuttleapp-260f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shuttleapp-260f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSsI1Lc42L05lN_bH6G3MdfANYb3t06u4',
    appId: '1:605657235035:ios:18e9ffca5ec9fd9358897e',
    messagingSenderId: '605657235035',
    projectId: 'shuttleapp-260f8',
    databaseURL: 'https://shuttleapp-260f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shuttleapp-260f8.firebasestorage.app',
    iosBundleId: 'com.example.shuttlego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSsI1Lc42L05lN_bH6G3MdfANYb3t06u4',
    appId: '1:605657235035:ios:18e9ffca5ec9fd9358897e',
    messagingSenderId: '605657235035',
    projectId: 'shuttleapp-260f8',
    databaseURL: 'https://shuttleapp-260f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shuttleapp-260f8.firebasestorage.app',
    iosBundleId: 'com.example.shuttlego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyxAQfM_tmh4k7S7S0Kl2C1hL7so5qv68',
    appId: '1:605657235035:web:925be7cb69c2c3a958897e',
    messagingSenderId: '605657235035',
    projectId: 'shuttleapp-260f8',
    authDomain: 'shuttleapp-260f8.firebaseapp.com',
    databaseURL: 'https://shuttleapp-260f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shuttleapp-260f8.firebasestorage.app',
  );
}
